### ISSUE TITLE
Notes on the implicit test

### ISSUE THREAD

**Issue by gassechen** [youngde811/Lisa#10]
```
(defrule turn-on-heater ()
  (ambient-temperature (current-temperature ?ct) 
                       (desired-temperature ?dt (< ?ct ?dt))
		       (location ?loc))
  
  (test (equal ?loc "room"))
  =>
  (assert (heater-state (state on)))
  (print "Turning on the heater"))
```

```
; processing (DEFRULE TURN-ON-HEATER ...); in: LAMBDA ()
;     (< LISA-HEATER::?CT LISA-HEATER::?DT)
; 
; note: unable to
;   open-code FLOAT to RATIONAL comparison
; due to type uncertainty:
;   The first argument is a REAL, not a SINGLE-FLOAT.
;   The second argument is a REAL, not a RATIONAL.
; 
; note: unable to
;   open-code FLOAT to RATIONAL comparison
; due to type uncertainty:
;   The first argument is a REAL, not a DOUBLE-FLOAT.
;   The second argument is a REAL, not a RATIONAL.
; 
; note: forced to do GENERIC-< (cost 10)
;       unable to do inline float comparison (cost 3) because:
;       The first argument is a REAL, not a SINGLE-FLOAT.
;       The second argument is a REAL, not a SINGLE-FLOAT.
;       unable to do inline float comparison (cost 3) because:
;       The first argument is a REAL, not a DOUBLE-FLOAT.
;       The second argument is a REAL, not a DOUBLE-FLOAT.
;       etc.
; 
; compilation unit finished
;   printed 3 notes
```
However, if I use the test this way, there is no problem.
```
(defrule turn-on-heater ()
  (ambient-temperature (current-temperature ?ct) 
                       (desired-temperature ?dt )
                       (location ?loc))
  
  (test (and (equal ?loc "room")
	     (< ?ct ?dt)))
  =>
  (assert (heater-state (state on)))
  (print "Turning on the heater"))
```

**Comment by gassechen** [comment]
It seems to be in this function.
It is not a simple thing, because any modification I make is always more expensive for the compiler.
 ```
(defun make-intra-pattern-test (slot)
  (let ((test
         (function
          (lambda (tokens)
            (declare (optimize (speed 3) (debug 1) (safety 0)))
            (equal (get-slot-value (token-top-fact tokens)
                                   (pattern-slot-name slot))
                   (get-slot-value (token-top-fact tokens)
                                   (binding-slot-name 
                                    (pattern-slot-slot-binding slot))))))))
    (if (negated-slot-p slot) (complement test) test)))
```

**Comment by youngde811** [comment]
Thanks for the report! I’ll take a look a see what’s causing the issue. Cheers!

David

Lasciate ogne speranza, voi ch’intrate.

**Comment by youngde811** [comment]
Ok, don’t worry about this. The SBCL compiler/optimizer is a strange beast, and can often yield false negatives. I’ll be digging deeper into optimizations these next few months, and will also be trying other Lisp implementations. In fact, the LispWorks optimizer is extremely good.

So we’ll see what we can see.

Cheers David.

Lasciate ogne speranza, voi ch’intrate.

**Comment by youngde811** [comment]
It is indeed an odd scenario, isn’t it?

**Comment by youngde811** [comment]
> ```
> (defrule turn-on-heater ()
>   (ambient-temperature (current-temperature ?ct) 
>                        (desired-temperature ?dt (< ?ct ?dt))
> 		       (location ?loc))
>   
>   (test (equal ?loc "room"))
>   =>
>   (assert (heater-state (state on)))
>   (print "Turning on the heater"))
> ```
> 
> ```
> ; processing (DEFRULE TURN-ON-HEATER ...); in: LAMBDA ()
> ;     (< LISA-HEATER::?CT LISA-HEATER::?DT)
> ; 
> ; note: unable to
> ;   open-code FLOAT to RATIONAL comparison
> ; due to type uncertainty:
> ;   The first argument is a REAL, not a SINGLE-FLOAT.
> ;   The second argument is a REAL, not a RATIONAL.
> ; 
> ; note: unable to
> ;   open-code FLOAT to RATIONAL comparison
> ; due to type uncertainty:
> ;   The first argument is a REAL, not a DOUBLE-FLOAT.
> ;   The second argument is a REAL, not a RATIONAL.
> ; 
> ; note: forced to do GENERIC-< (cost 10)
> ;       unable to do inline float comparison (cost 3) because:
> ;       The first argument is a REAL, not a SINGLE-FLOAT.
> ;       The second argument is a REAL, not a SINGLE-FLOAT.
> ;       unable to do inline float comparison (cost 3) because:
> ;       The first argument is a REAL, not a DOUBLE-FLOAT.
> ;       The second argument is a REAL, not a DOUBLE-FLOAT.
> ;       etc.
> ; 
> ; compilation unit finished
> ;   printed 3 notes
> ```
> 
> However, if I use the test this way, there is no problem.
> 
> ```
> (defrule turn-on-heater ()
>   (ambient-temperature (current-temperature ?ct) 
>                        (desired-temperature ?dt )
>                        (location ?loc))
>   
>   (test (and (equal ?loc "room")
> 	     (< ?ct ?dt)))
>   =>
>   (assert (heater-state (state on)))
>   (print "Turning on the heater"))
> ```

I would also search CLtL2 for the various type specific comparators, and try them in your constraint form, seeing if SBCL is able to optimize without clues.

**Comment by youngde811** [comment]
Oh, and another thought. MAKE-INTRA-PATTERN-TEST is not the place to introduce DECLARE forms for optimization. The compiler has no idea of types as the Rete network is formed via rule LHSs, and it’s not possible to do so in the present language. Yes, tests are given to the Lisp compiler, but there’s no context for it to deduce types.

**Comment by youngde811** [comment]
Will address during further optimization work.
