### ISSUE TITLE
globally declaring the FTYPE of CLASS-NAME while in package LISA.

### ISSUE THREAD

**Issue by gassechen** [youngde811/Lisa#6]
Hello, I am trying to install Lisa, but this version of github gives me the following error
 ``Lock on package COMMON-LISP violated when
globally declaring the FTYPE of CLASS-NAME while in package LISA.
 [Condition of type SYMBOL-PACKAGE-LOCKED-ERROR]
See also:
 SBCL Manual, Package Locks [:node]
 Common Lisp Hyperspec, 11.1.2.1.2 [:section]``

This is SBCL 2.4.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

**I hit unlock package and compiled successfully.**

**Comment by youngde811** [comment]
Hi! Did you use install.lisp to configure and load Lisa? That code unlocks package COMMON-LISP for SBCL. There’s a bug in Lisa somewhere that is attempting to create a symbol in COMMON-LISP; that’s incorrect and I need to locate and fix it. 

Until then, if you simply _(load “install”)_ from the SBCL REPL you should be fine. Cheers!

**Comment by gassechen** [comment]
Now I am using this
 ```
(ql:quickload :lisa)
To load "lisa":
 Install 1 Quicklisp release:
 johanlindberg-lisa
; Fetching #<URL "http://dist.ultralisp.org/archive/609/johanlindberg-lisa-20210914222959.tgz">
; 164.72KB
==================================================================
168,674 bytes in 1.13 seconds (145.90KB/sec)
; Loading "lisa"
[package lisa]..................................
[package lisa-user]...............................
[package lisa.reflect]..............................
[package lisa.belief]..............................
[package lisa.heap]...............................
[package lisa.utils]..............................
..................................................
[package lisa-lisp]
(:LISA)
`````
I am doing a very basic test because I have no experience with this type of systems
```
;; Templates
(deftemplate ambient_temperature()
 (slot current_temperature)
 (slot desired_temperature)
 (slot location))

(deftemplate heater_state()
 (slot state))

;; rules
(defrule turn_on_heater()
 (ambient_temperature (current_temperature ?ct)
 (desired_temperature ?dt)
 (location ?loc))
 (test (< ?ct ?dt))
 =>
 (assert(heater_state(state on)))
 (print "Turning on the heater")

(defrule turn_off_heater()
 (ambient_temperature (current_temperature ?ct)
 (desired_temperature ?dt)
 (location ?loc))
 (test (>= ?ct ?dt))
 =>
 (assert(heater_state(state off)))
 (print "Turning off the heater")

;; Simulation
(defun heater_simulation()
 ;; Initialize the system state
 (reset)
 (assert (ambient_temperature (current_temperature 20)
 (desired_temperature 22)
 (location "room")))

 (loop
 do
 ;; Run the inference engine
 (run)

 ;; Add a new ambient temperature fact
 (assert(ambient_temperature(current_temperature(+10(random 20)))
 (desired_temperature 22)
 (location "room")))

 ;; Pause for 10 seconds
 (sleep 10)))
```

```
LISA> (simulador-calefaccion)

"Encendiendo calefactor" 
"Encendiendo calefactor" 
"Encendiendo calefactor" 
"Encendiendo calefactor" 
"Apagando calefactor" 
"Apagando calefactor" 
"Encendiendo calefactor" 
```

With the github version, when I execute run it does not load the rules. In a while I'm going to install it as you suggested and I'll let you know how it goes.

**Comment by youngde811** [comment]
Ah, gotcha. So I'd first suggest reading all of the documentation for Lisa, as there are simple examples that might help. Second, I like your use of Quicklisp to install Lisa, but I need to move some code around so that mechanism works properly. For now, I'd suggest cloning the Lisa repository. I can have the QL version of Lisa ready in a few days.

Try not to run your rulesets within the LISA package; that's intended to be internal. Use perhaps LISA-LISP, or one of your own creation.

Let me know your progress; I'll help where I can. Thanks!

**Comment by gassechen** [comment]
> Ah, gotcha. So I'd first suggest reading all of the documentation for Lisa, as there are simple examples that might help. Second, I like your use of Quicklisp to install Lisa, but I need to move some code around so that mechanism works properly. For now, I'd suggest cloning the Lisa repository. I can have the QL version of Lisa ready in a few days.
> 
> Try not to run your rulesets within the LISA package; that's intended to be internal. Use perhaps LISA-LISP, or one of your own creation.
> 
> Let me know your progress; I'll help where I can. Thanks!
Ok, thanks for your reply. I intend to use Lisa to integrate facts from machine learning models I have in python. I have a computer vision application with YOLO and I want the output of the inference to be facts for Lisa, so I can apply reasoning to those models.

**Comment by youngde811** [comment]
Those SBCL notes are ok; they're from the compiler and optimizer.

So, here's how I'm working right now:

1. From within Emacs, M-x slime to start SBCL. You can of course start SBCL some other way.
2. Run: _(load "install")_.
3. Run: _(load "examples/mab")_.
4. Run: _(in-package :lisa-mab)_.
5. Run: _(run-mab)_.

The above runs the Monkey and Bananas planning problem. Note that RUN does NOT load your ruleset; you must do that using LOAD or some similar mechanism. The DEFRULE forms compile your rules into a Rete network. Once your rulebase is loaded, you'll ASSERT some facts. Then you may invoke RUN. Have a look at examples/mab.lisp and examples/mycin.lisp for good examples.

**Comment by gassechen** [comment]
> Hi! Did you use install.lisp to configure and load Lisa? That code unlocks package COMMON-LISP for SBCL. There’s a bug in Lisa somewhere that is attempting to create a symbol in COMMON-LISP; that’s incorrect and I need to locate and fix it.
> 
> Until then, if you simply _(load “install”)_ from the SBCL REPL you should be fine. Cheers!



> Hi! Did you use install.lisp to configure and load Lisa? That code unlocks package COMMON-LISP for SBCL. There’s a bug in Lisa somewhere that is attempting to create a symbol in COMMON-LISP; that’s incorrect and I need to locate and fix it.
> 
> Until then, if you simply _(load “install”)_ from the SBCL REPL you should be fine. Cheers!

ok. clone the github repository
`CL-USER> (load "/home/mtk/quicklisp/local-projects/Lisa/install.lisp")`
it compiled without errors.
I moved to `lisa-user> (heater-simulation) `, it loads the facts but does not trigger the rules.
that is the difference between the github repository and the download from quicklisp

**Comment by youngde811** [comment]
The RUN function actually starts the inference engine. Also, note that RESET must be used before loading facts, if you have rules with an empty LHS; these rule types match just the INITIAL-FACT, which RESET asserts.

**Comment by youngde811** [comment]
I'm going to try your code and see what I get.

**Comment by youngde811** [comment]
Try this. Your code should work, as the TEST conditional element is a reasonable choice here. In the meantime, I'll do some experiments with the TEST CE, as it has worked since the beginning. Thanks!

```lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
  (when (not (find-package "LISA-HEATER"))
    (defpackage "LISA-HEATER"
      (:use "LISA-LISP")
      (:export "HEATER-SIMULATION"))))

(in-package "LISA-HEATER")

(make-inference-engine)

(deftemplate ambient-temperature ()
  (slot current-temperature)
  (slot desired-temperature)
  (slot location))

(deftemplate heater-state ()
  (slot state))

;; Rules

(defrule turn-on-heater ()
  (ambient-temperature (current-temperature ?ct) 
                       (desired-temperature ?dt (< ?ct ?dt))
                       (location ?loc))
  ; (test (< ?ct ?dt))
  =>
  (assert (heater-state (state on)))
  (print "Turning on the heater"))

(defrule turn-off-heater ()
  (ambient-temperature (current-temperature ?ct) 
                       (desired-temperature ?dt (>= ?ct ?dt))
                       (location ?loc))
  ; (test (>= ?ct ?dt))
  =>
  (assert (heater-state (state off)))
  (print "Turning off the heater"))

;; Simulation

(defun heater-simulation ()
  ;; Initialize the system state
  (reset)
  (assert (ambient-temperature (current-temperature 20)
                                (desired-temperature 22)
                                (location "room")))
  (loop
    do
      ;; Execute the inference engine
      (run)

      ;; Add a new ambient-temperature fact
      (assert (ambient-temperature (current-temperature (+ 10 (random 20)))
                                    (desired-temperature 22)
                                    (location "room")))

      ;; Pause for 10 seconds
      (sleep 10)))
```

**Comment by youngde811** [comment]
Hmm... The TEST CE might be broken on SBCL. Very interesting. Thanks for reporting this! I'll keep you posted.

Cheers!

**Comment by youngde811** [comment]
> > Ah, gotcha. So I'd first suggest reading all of the documentation for Lisa, as there are simple examples that might help. Second, I like your use of Quicklisp to install Lisa, but I need to move some code around so that mechanism works properly. For now, I'd suggest cloning the Lisa repository. I can have the QL version of Lisa ready in a few days.
> > Try not to run your rulesets within the LISA package; that's intended to be internal. Use perhaps LISA-LISP, or one of your own creation.
> > Let me know your progress; I'll help where I can. Thanks!
> > Ok, thanks for your reply. I intend to use Lisa to integrate facts from machine learning models I have in python. I have a computer vision application with YOLO and I want the output of the inference to be facts for Lisa, so I can apply reasoning to those models.

Very cool. Love to hear how folks are using Lisa. Cheers!

**Comment by youngde811** [comment]
Update: I plan to have a fix out for the TEST conditional element out within a week or so. Apologies for the delay, but Christmas and family…

Also out will be more performance improvements. Meanwhile, the workaround is to use constraints as I illustrated above. In your particular case, they’re a bit more efficient, too. 

Cheers!

**Comment by gassechen** [comment]
> Try this. Your code should work, as the TEST conditional element is a reasonable choice here. In the meantime, I'll do some experiments with the TEST CE, as it has worked since the beginning. Thanks!
If you don't mind, I'm not in a hurry. I'm going to work with the Quicklisp version in the meantime, so I can learn about this type of system, since I'm a novice. I'd like to collaborate more but my knowledge of Lisp is limited, this great language that I discovered a year ago is no longer in fashion. Happy holidays, may you spend it in peace and with your family.
Regards.
Gaston Pepe from Patagonia, Argentina

**Comment by youngde811** [comment]
> > Try this. Your code should work, as the TEST conditional element is a reasonable choice here. In the meantime, I'll do some experiments with the TEST CE, as it has worked since the beginning. Thanks!
> > If you don't mind, I'm not in a hurry. I'm going to work with the Quicklisp version in the meantime, so I can learn about this type of system, since I'm a novice. I'd like to collaborate more but my knowledge of Lisp is limited, this great language that I discovered a year ago is no longer in fashion. Happy holidays, may you spend it in peace and with your family.
> > Regards.
> > Gaston Pepe from Patagonia, Argentina

Hi Gaston! Thank you very much for your kind words. Peace to you and yours, as well.

I spent some time today investigating this issue. I've discovered that during the many years I was away from Lisa, there were commits to the Sourceforge repository that broke the TEST conditional element. There is code I do not recognize, and looking at the Rete network tells me someone broke the parser for the TEST CE.

No worries. Shouldn't be a difficult fix. In the meantime, do not worry that Lisp is not "in fashion". It's the best programming environment and language ever created, and the Lisp community is fortunate that people like yourself continue to be acquainted with it.

Lisp is not dead; believe me. It is used commercially for complex systems, and is a remarkable language. Enjoy your journey, and Merry Christmas!

I'll keep you posted on progress. Thank you again!

**Comment by youngde811** [comment]
Bingo! Found the bug! Yup, someone either committed a botched source file, or misunderstood the TEST CE. My guess is it was an accident, but it's been ten years since I've looked at Lisa so who knows?

In any event, I'll have a new release before Christmas. Thanks so much for catching this bug; good work!

**Comment by youngde811** [comment]
Fixed in latest release.

**Comment by youngde811** [comment]
Fixed in latest release.
